##===- lib/Transforms/Hello/Makefile -----------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL = ../..
LIBRARYNAME = instrument 
SHARED_LIBRARY = 1
ARCHIVE_LIBRARY = 1
USEDLIBS =  

CFLAGS += -g

include $(LEVEL)/Makefile.common

